Avoid UNIMPLEMENTED: The emulator does not support the PLAN query mode. - Statement: 'SELECT * FROM '
```
❯ embulk run example/config.yml -Ibuild/gemContents/lib -X min_output_tasks=2
2021-11-05 22:39:32.350 +0900: Embulk v0.9.23
2021-11-05 22:39:33.285 +0900 [WARN] (main): DEPRECATION: JRuby org.jruby.embed.ScriptingContainer is directly injected.
2021-11-05 22:39:35.447 +0900 [INFO] (main): Gem's home and path are set by default: "/Users/takahiro.nakayama/.embulk/lib/gems"
2021-11-05 22:39:36.344 +0900 [INFO] (main): Started Embulk v0.9.23
2021-11-05 22:39:36.446 +0900 [INFO] (0001:transaction): Loaded plugin embulk/input/spanner from a load path
2021-11-05 22:39:36.506 +0900 [WARN] (0001:transaction): "UTC" is recognized as "Z" to be compatible with the legacy style.
2021-11-05 22:39:37.522 +0900 [INFO] (0001:transaction): Using JDBC Driver 2.0
org.embulk.exec.PartialExecutionException: java.lang.RuntimeException: com.google.cloud.spanner.jdbc.JdbcSqlExceptionFactory$JdbcSqlExceptionImpl: UNIMPLEMENTED: io.grpc.StatusRuntimeException: UNIMPLEMENTED: The emulator does not support the PLAN query mode. - Statement: 'SELECT * FROM `Singers`'
        at org.embulk.exec.BulkLoader$LoaderState.buildPartialExecuteException(BulkLoader.java:340)
        at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:566)
        at org.embulk.exec.BulkLoader.access$000(BulkLoader.java:35)
        at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:353)
        at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:350)
        at org.embulk.spi.Exec.doWith(Exec.java:22)
        at org.embulk.exec.BulkLoader.run(BulkLoader.java:350)
        at org.embulk.EmbulkEmbed.run(EmbulkEmbed.java:242)
        at org.embulk.EmbulkRunner.runInternal(EmbulkRunner.java:291)
        at org.embulk.EmbulkRunner.run(EmbulkRunner.java:155)
        at org.embulk.cli.EmbulkRun.runSubcommand(EmbulkRun.java:431)
        at org.embulk.cli.EmbulkRun.run(EmbulkRun.java:90)
        at org.embulk.cli.Main.main(Main.java:64)
        Suppressed: java.lang.NullPointerException
                at org.embulk.exec.BulkLoader.doCleanup(BulkLoader.java:463)
                at org.embulk.exec.BulkLoader$3.run(BulkLoader.java:397)
                at org.embulk.exec.BulkLoader$3.run(BulkLoader.java:394)
                at org.embulk.spi.Exec.doWith(Exec.java:22)
                at org.embulk.exec.BulkLoader.cleanup(BulkLoader.java:394)
                at org.embulk.EmbulkEmbed.run(EmbulkEmbed.java:245)
                ... 5 more
Caused by: java.lang.RuntimeException: com.google.cloud.spanner.jdbc.JdbcSqlExceptionFactory$JdbcSqlExceptionImpl: UNIMPLEMENTED: io.grpc.StatusRuntimeException: UNIMPLEMENTED: The emulator does not support the PLAN query mode. - Statement: 'SELECT * FROM `Singers`'
        at org.embulk.input.jdbc.AbstractJdbcInputPlugin.transaction(AbstractJdbcInputPlugin.java:228)
        at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:507)
        ... 11 more
Caused by: com.google.cloud.spanner.jdbc.JdbcSqlExceptionFactory$JdbcSqlExceptionImpl: UNIMPLEMENTED: io.grpc.StatusRuntimeException: UNIMPLEMENTED: The emulator does not support the PLAN query mode. - Statement: 'SELECT * FROM `Singers`'
        at com.google.cloud.spanner.jdbc.JdbcSqlExceptionFactory.of(JdbcSqlExceptionFactory.java:222)
        at com.google.cloud.spanner.jdbc.AbstractJdbcStatement.executeQuery(AbstractJdbcStatement.java:194)
        at com.google.cloud.spanner.jdbc.AbstractJdbcStatement.analyzeQuery(AbstractJdbcStatement.java:162)
        at com.google.cloud.spanner.jdbc.JdbcPreparedStatement.getMetaData(JdbcPreparedStatement.java:114)
        at org.embulk.input.jdbc.JdbcInputConnection.getSchemaOfQuery(JdbcInputConnection.java:64)
        at org.embulk.input.jdbc.AbstractJdbcInputPlugin.setupTask(AbstractJdbcInputPlugin.java:260)
        at org.embulk.input.jdbc.AbstractJdbcInputPlugin.transaction(AbstractJdbcInputPlugin.java:223)
        ... 12 more
Caused by: com.google.cloud.spanner.SpannerException: UNIMPLEMENTED: io.grpc.StatusRuntimeException: UNIMPLEMENTED: The emulator does not support the PLAN query mode. - Statement: 'SELECT * FROM `Singers`'
        at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerExceptionPreformatted(SpannerExceptionFactory.java:284)
        at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerException(SpannerExceptionFactory.java:170)
        at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerException(SpannerExceptionFactory.java:110)
        at com.google.cloud.spanner.AbstractResultSet$GrpcStreamIterator.computeNext(AbstractResultSet.java:912)
        at com.google.cloud.spanner.AbstractResultSet$GrpcStreamIterator.computeNext(AbstractResultSet.java:843)
        at embulk.input.spanner.com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
        at embulk.input.spanner.com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
        at com.google.cloud.spanner.AbstractResultSet$ResumableStreamIterator.computeNext(AbstractResultSet.java:1094)
        at com.google.cloud.spanner.AbstractResultSet$ResumableStreamIterator.computeNext(AbstractResultSet.java:966)
        at embulk.input.spanner.com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
        at embulk.input.spanner.com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
        at com.google.cloud.spanner.AbstractResultSet$GrpcValueIterator.ensureReady(AbstractResultSet.java:269)
        at com.google.cloud.spanner.AbstractResultSet$GrpcValueIterator.getMetadata(AbstractResultSet.java:245)
        at com.google.cloud.spanner.AbstractResultSet$GrpcResultSet.next(AbstractResultSet.java:119)
        at com.google.cloud.spanner.ForwardingResultSet.next(ForwardingResultSet.java:54)
        at com.google.cloud.spanner.SessionPool$AutoClosingReadContext$1.internalNext(SessionPool.java:272)
        at com.google.cloud.spanner.SessionPool$AutoClosingReadContext$1.next(SessionPool.java:252)
        at com.google.cloud.spanner.connection.DirectExecuteResultSet.<init>(DirectExecuteResultSet.java:63)
        at com.google.cloud.spanner.connection.DirectExecuteResultSet.ofResultSet(DirectExecuteResultSet.java:57)
        at com.google.cloud.spanner.connection.AbstractMultiUseTransaction.lambda$executeQueryAsync$0(AbstractMultiUseTransaction.java:71)
        at io.grpc.Context$2.call(Context.java:596)
        at embulk.input.spanner.com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
        at embulk.input.spanner.com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
        at embulk.input.spanner.com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        Suppressed: com.google.cloud.spanner.connection.AbstractBaseUnitOfWork$SpannerAsyncExecutionException: Execution failed for statement: SELECT * FROM `Singers`
                at com.google.cloud.spanner.connection.AbstractBaseUnitOfWork.executeStatementAsync(AbstractBaseUnitOfWork.java:233)
                at com.google.cloud.spanner.connection.AbstractBaseUnitOfWork.executeStatementAsync(AbstractBaseUnitOfWork.java:145)
                at com.google.cloud.spanner.connection.AbstractMultiUseTransaction.executeQueryAsync(AbstractMultiUseTransaction.java:67)
                at com.google.cloud.spanner.connection.ConnectionImpl.internalExecuteQuery(ConnectionImpl.java:1043)
                at com.google.cloud.spanner.connection.ConnectionImpl.parseAndExecuteQuery(ConnectionImpl.java:874)
                at com.google.cloud.spanner.connection.ConnectionImpl.analyzeQuery(ConnectionImpl.java:853)
                at com.google.cloud.spanner.jdbc.AbstractJdbcStatement.executeQuery(AbstractJdbcStatement.java:190)
                at com.google.cloud.spanner.jdbc.AbstractJdbcStatement.analyzeQuery(AbstractJdbcStatement.java:162)
                at com.google.cloud.spanner.jdbc.JdbcPreparedStatement.getMetaData(JdbcPreparedStatement.java:114)
                at org.embulk.input.jdbc.JdbcInputConnection.getSchemaOfQuery(JdbcInputConnection.java:64)
                at org.embulk.input.jdbc.AbstractJdbcInputPlugin.setupTask(AbstractJdbcInputPlugin.java:260)
                at org.embulk.input.jdbc.AbstractJdbcInputPlugin.transaction(AbstractJdbcInputPlugin.java:223)
                at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:507)
                at org.embulk.exec.BulkLoader.access$000(BulkLoader.java:35)
                at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:353)
                at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:350)
                at org.embulk.spi.Exec.doWith(Exec.java:22)
                at org.embulk.exec.BulkLoader.run(BulkLoader.java:350)
                at org.embulk.EmbulkEmbed.run(EmbulkEmbed.java:242)
                at org.embulk.EmbulkRunner.runInternal(EmbulkRunner.java:291)
                at org.embulk.EmbulkRunner.run(EmbulkRunner.java:155)
                at org.embulk.cli.EmbulkRun.runSubcommand(EmbulkRun.java:431)
                at org.embulk.cli.EmbulkRun.run(EmbulkRun.java:90)
                at org.embulk.cli.Main.main(Main.java:64)
Caused by: com.google.cloud.spanner.SpannerException: UNIMPLEMENTED: io.grpc.StatusRuntimeException: UNIMPLEMENTED: The emulator does not support the PLAN query mode. - Statement: 'SELECT * FROM `Singers`'
        at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerExceptionPreformatted(SpannerExceptionFactory.java:284)
        at com.google.cloud.spanner.AbstractResultSet$GrpcStreamIterator$ConsumerImpl.onError(AbstractResultSet.java:948)
        at com.google.cloud.spanner.spi.v1.GapicSpannerRpc$SpannerResponseObserver.onError(GapicSpannerRpc.java:1789)
        at com.google.api.gax.tracing.TracedResponseObserver.onError(TracedResponseObserver.java:103)
        at com.google.api.gax.rpc.RetryingServerStreamingCallable$1.onFailure(RetryingServerStreamingCallable.java:99)
        at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
        at embulk.input.spanner.com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1074)
        at embulk.input.spanner.com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
        at embulk.input.spanner.com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1213)
        at embulk.input.spanner.com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:983)
        at embulk.input.spanner.com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:771)
        at com.google.api.gax.retrying.BasicRetryingFuture.handleAttempt(BasicRetryingFuture.java:200)
        at com.google.api.gax.retrying.CallbackChainRetryingFuture$AttemptCompletionListener.handle(CallbackChainRetryingFuture.java:135)
        at com.google.api.gax.retrying.CallbackChainRetryingFuture$AttemptCompletionListener.run(CallbackChainRetryingFuture.java:117)
        at embulk.input.spanner.com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
        at embulk.input.spanner.com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1213)
        at embulk.input.spanner.com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:983)
        at embulk.input.spanner.com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:771)
        at com.google.api.core.AbstractApiFuture$InternalSettableFuture.setException(AbstractApiFuture.java:95)
        at com.google.api.core.AbstractApiFuture.setException(AbstractApiFuture.java:77)
        at com.google.api.core.SettableApiFuture.setException(SettableApiFuture.java:52)
        at com.google.api.gax.rpc.ServerStreamingAttemptCallable.onAttemptError(ServerStreamingAttemptCallable.java:378)
        at com.google.api.gax.rpc.ServerStreamingAttemptCallable.access$600(ServerStreamingAttemptCallable.java:97)
        at com.google.api.gax.rpc.ServerStreamingAttemptCallable$2.onErrorImpl(ServerStreamingAttemptCallable.java:249)
        at com.google.api.gax.rpc.StateCheckingResponseObserver.onError(StateCheckingResponseObserver.java:86)
        at com.google.api.gax.rpc.Watchdog$WatchdogStream.onErrorImpl(Watchdog.java:284)
        at com.google.api.gax.rpc.StateCheckingResponseObserver.onError(StateCheckingResponseObserver.java:86)
        at com.google.api.gax.grpc.ExceptionResponseObserver.onErrorImpl(ExceptionResponseObserver.java:84)
        at com.google.api.gax.rpc.StateCheckingResponseObserver.onError(StateCheckingResponseObserver.java:86)
        at com.google.api.gax.grpc.GrpcDirectStreamController$ResponseObserverAdapter.onClose(GrpcDirectStreamController.java:149)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at com.google.cloud.spanner.spi.v1.SpannerErrorInterceptor$1$1.onClose(SpannerErrorInterceptor.java:100)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:557)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:69)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:738)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:717)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        ... 3 more
Caused by: com.google.cloud.spanner.SpannerException: UNIMPLEMENTED: io.grpc.StatusRuntimeException: UNIMPLEMENTED: The emulator does not support the PLAN query mode.
        at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerExceptionPreformatted(SpannerExceptionFactory.java:284)
        at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerException(SpannerExceptionFactory.java:61)
        at com.google.cloud.spanner.SpannerExceptionFactory.fromApiException(SpannerExceptionFactory.java:299)
        at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerException(SpannerExceptionFactory.java:174)
        at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerException(SpannerExceptionFactory.java:110)
        ... 45 more
Caused by: io.grpc.StatusRuntimeException: UNIMPLEMENTED: The emulator does not support the PLAN query mode.
        at io.grpc.Status.asRuntimeException(Status.java:535)
        ... 18 more

Error: java.lang.RuntimeException: com.google.cloud.spanner.jdbc.JdbcSqlExceptionFactory$JdbcSqlExceptionImpl: UNIMPLEMENTED: io.grpc.StatusRuntimeException: UNIMPLEMENTED: The emulator does not support the PLAN query mode. - Statement: 'SELECT * FROM `Singers`'
```